Repository sablier-labs/examples, pull requests merged in 2023-07, with the labels that each got.

#8 fix: bump pragma to >=0.8.19
  v2/core/LockupDynamicStreamCreator.sol
  v2/core/LockupLinearStreamCreator.sol
  v2/core/LockupLinearStreamCreator.t.sol
  v2/core/StreamManagement.sol
Labels: bug

#4 Add periphery examples
  v2/core/LockupDynamicStreamCreator.sol
  v2/core/LockupLinearStreamCreator.t.sol
  v2/periphery/BatchLockupDynamicStreamCreator.sol
  v2/periphery/BatchLockupLinearStreamCreator.sol
  v2/periphery/BatchLockupLinearStreamCreator.t.sol
  v2/periphery/DeployProxyAndInstallPlugin.sol
Labels: feature

#13 Add ERC1271 and fix tests
  .gitignore
  foundry.toml
  v2/core/LockupLinearStreamCreator.t.sol
  v2/periphery/BatchLockupDynamicStreamCreator.sol
  v2/periphery/BatchLockupLinearStreamCreator.sol
  v2/periphery/BatchLockupLinearStreamCreator.t.sol
  v2/periphery/ERC1271.sol
  v2/periphery/SingleLockupDynamicStreamCreator.sol
  v2/periphery/SingleLockupLinearStreamCreator.sol
Labels: bug, testing
